"""003 alter txs

Revision ID: 2953a25ff995
Revises: 86dbc26e409c
Create Date: 2024-07-10 21:00:09.953174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2953a25ff995'
down_revision: Union[str, None] = '86dbc26e409c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('transaction_credit_account_idx'), 'transaction', ['credit_account'], unique=False)
    op.create_index(op.f('transaction_debit_account_idx'), 'transaction', ['debit_account'], unique=False)
    op.drop_constraint('transaction_credit_account_account_fkey', 'transaction', type_='foreignkey')
    op.drop_constraint('transaction_debit_account_account_fkey', 'transaction', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transaction_debit_account_account_fkey', 'transaction', 'account', ['debit_account'], ['number'])
    op.create_foreign_key('transaction_credit_account_account_fkey', 'transaction', 'account', ['credit_account'], ['number'])
    op.drop_index(op.f('transaction_debit_account_idx'), table_name='transaction')
    op.drop_index(op.f('transaction_credit_account_idx'), table_name='transaction')
    # ### end Alembic commands ###
