"""005 alter transactions

Revision ID: 2e2984a182a8
Revises: f7c05962f048
Create Date: 2024-07-08 21:07:45.545596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2984a182a8'
down_revision: Union[str, None] = 'f7c05962f048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('type', sa.String(length=128), nullable=True))
    op.create_index(op.f('transaction_type_idx'), 'transaction', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('transaction_type_idx'), table_name='transaction')
    op.drop_column('transaction', 'type')
    # ### end Alembic commands ###
