"""006 alter categories

Revision ID: 3866f4aaa2f7
Revises: 4c9fa74dc2b4
Create Date: 2024-08-21 18:55:14.421367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3866f4aaa2f7'
down_revision: Union[str, None] = '4c9fa74dc2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_category_for_user', 'category', type_='unique')
    op.create_unique_constraint('unique_category_for_user', 'category', ['name', 'user_id', 'deleted_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_category_for_user', 'category', type_='unique')
    op.create_unique_constraint('unique_category_for_user', 'category', ['name', 'user_id'])
    # ### end Alembic commands ###
