"""005 alter categories

Revision ID: 4c9fa74dc2b4
Revises: 65cbabff5d19
Create Date: 2024-08-21 17:43:34.363447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9fa74dc2b4'
down_revision: Union[str, None] = '65cbabff5d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('category_name_idx', table_name='category')
    op.create_index(op.f('category_name_idx'), 'category', ['name'], unique=False)
    op.create_unique_constraint('unique_category_for_user', 'category', ['name', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_category_for_user', 'category', type_='unique')
    op.drop_index(op.f('category_name_idx'), table_name='category')
    op.create_index('category_name_idx', 'category', ['name'], unique=True)
    # ### end Alembic commands ###
