"""002 add account balance txs

Revision ID: 86dbc26e409c
Revises: 5c5220775c09
Create Date: 2024-07-10 17:37:00.318055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86dbc26e409c'
down_revision: Union[str, None] = '5c5220775c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('account_owner_id_user_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('account_pkey'))
    )
    op.create_index(op.f('account_name_idx'), 'account', ['name'], unique=False)
    op.create_index(op.f('account_number_idx'), 'account', ['number'], unique=True)
    op.create_table('account_balance',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], name=op.f('account_balance_account_id_account_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('account_balance_pkey')),
    sa.UniqueConstraint('account_id', name=op.f('account_balance_account_id_key'))
    )
    op.create_table('transaction',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('credit_account', sa.String(length=128), nullable=True),
    sa.Column('debit_account', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['credit_account'], ['account.number'], name=op.f('transaction_credit_account_account_fkey')),
    sa.ForeignKeyConstraint(['debit_account'], ['account.number'], name=op.f('transaction_debit_account_account_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('transaction_user_id_user_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transaction_pkey'))
    )
    op.create_index(op.f('transaction_type_idx'), 'transaction', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('transaction_type_idx'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_table('account_balance')
    op.drop_index(op.f('account_number_idx'), table_name='account')
    op.drop_index(op.f('account_name_idx'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
