"""004 alter accounts

Revision ID: d6c730813091
Revises: 470faeda94aa
Create Date: 2024-07-05 17:32:51.661027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c730813091'
down_revision: Union[str, None] = '470faeda94aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'balance')
    # ### end Alembic commands ###
