"""007 alter transactions

Revision ID: ec3f3521f102
Revises: 3866f4aaa2f7
Create Date: 2024-08-22 14:58:10.413727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3f3521f102'
down_revision: Union[str, None] = '3866f4aaa2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('transaction_category_id_category_fkey'), 'transaction', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transaction_category_id_category_fkey'), 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'category_id')
    # ### end Alembic commands ###
